# fly.toml app configuration file generated for cirqus-swell-dev on 2023-09-14T08:01:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cirqus-swell-dev"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
